training:
  model_name_or_path: "distilgpt2"
  output_dir: "./checkpoints/full_train"
  num_train_epochs: 5
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  learning_rate: 5e-5
  warmup_steps: 200
  logging_steps: 100
  save_steps: 1000
  eval_steps: 1000
  max_seq_length: 512
  use_peft: false
  device: "auto"
  fp16: true
  seed: 42

data:
  data_path: "./data"
  text_column: "text"
  label_column: "label"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  max_examples: null
  cache_dir: "./data/cache"

eval:
  batch_size: 4
  max_new_tokens: 100
  temperature: 0.7
  top_k: 50
  top_p: 0.9
  num_beams: 1
  do_sample: true
  compute_metrics: true

api:
  openai_api_key: null
  openrouter_base_url: "https://openrouter.ai/api/v1"
  openrouter_model: "openrouter/auto"
  use_openrouter_fallback: true
  max_retries: 3
  timeout: 30